CREATE TABLE IF NOT EXISTS public.user_orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    cart_items JSONB NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    payment_method TEXT NOT NULL CHECK (payment_method IN ('bkash', 'nagad', 'bank')),
    billing_name TEXT NOT NULL,
    billing_phone TEXT NOT NULL,
    billing_email TEXT,
    billing_address TEXT NOT NULL,
    billing_city TEXT NOT NULL,
    billing_district TEXT NOT NULL,
    billing_country TEXT NOT NULL,
    billing_postal TEXT,
    shipping_name TEXT NOT NULL,
    shipping_phone TEXT NOT NULL,
    shipping_email TEXT,
    shipping_address TEXT NOT NULL,
    shipping_city TEXT NOT NULL,
    shipping_district TEXT NOT NULL,
    shipping_country TEXT NOT NULL,
    shipping_postal TEXT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
